from typing import Final

from app.external import JsonMap, UpstreamServiceError
from app.intelligence.models import CausalDiagnosis, DealBriefing, NextBestAction, RiskFlag

DEMO_DEAL_ID: Final = "deal_northstar_expansion"
DEMO_ATLAS_DEAL_ID: Final = "deal_atlas_renewal"
DEMO_MEMORY_ID: Final = "deal_northstar_expansion:deal_memory:2026-03-04T15:00:00.000Z"
DEMO_SOURCE_FACT_ID: Final = "source_fact_crm_stage"
DEMO_INTEGRATION_FACT_ID: Final = "integration_fact_crm_amount"


# allow: SIZE_OK — local demo seed fixture stays in one table for route parity.
def demo_records(tenant_id: str, deal_id: str) -> tuple[JsonMap, ...]:
    if deal_id != DEMO_DEAL_ID:
        raise UpstreamServiceError(service="local-demo", detail=f"missing seeded deal {deal_id}")
    return (
        {
            "record_type": "tenant",
            "id": tenant_id,
            "name": "Northstar Robotics",
            "domain": "northstar.example",
            "environment": "test",
        },
        {
            "record_type": "account",
            "id": "account_northstar",
            "tenant_id": tenant_id,
            "name": "Northstar Robotics",
            "domain": "northstar.example",
            "owner_user_id": "user_maya",
            "segment": "Enterprise robotics",
            "health": "at_risk",
            "renewal_date": None,
        },
        {
            "record_type": "account",
            "id": "account_atlas",
            "tenant_id": tenant_id,
            "name": "Atlas Medical Group",
            "domain": "atlas.example",
            "owner_user_id": "user_owen",
            "segment": "Healthcare",
            "health": "healthy",
            "renewal_date": "2026-03-31",
        },
        {
            "record_type": "role",
            "id": "role_sales_rep",
            "tenant_id": tenant_id,
            "name": "Sales rep",
            "permissions": ["deal:read", "call:read", "task:read"],
        },
        {
            "record_type": "role",
            "id": "role_admin",
            "tenant_id": tenant_id,
            "name": "Admin",
            "permissions": ["admin:read", "audit:read", "export:read"],
        },
        {
            "record_type": "user",
            "id": "user_maya",
            "tenant_id": tenant_id,
            "name": "Maya Chen",
            "email": "maya@novaridge.example",
            "role_id": "role_sales_rep",
            "role_name": "Sales rep",
            "manager_id": None,
            "status": "active",
        },
        {
            "record_type": "user",
            "id": "user_owen",
            "tenant_id": tenant_id,
            "name": "Owen Patel",
            "email": "owen@novaridge.example",
            "role_id": "role_sales_rep",
            "role_name": "Sales rep",
            "manager_id": None,
            "status": "active",
        },
        {
            "record_type": "admin_setting",
            "id": "admin_setting_exports",
            "tenant_id": tenant_id,
            "key": "exports.enabled",
            "value": "true",
            "updated_at": "2026-03-04T17:00:00.000Z",
        },
        {
            "record_type": "deal",
            "tenant_id": tenant_id,
            "deal_id": deal_id,
            "id": deal_id,
            "account_name": "Northstar Robotics",
            "name": "Northstar Robotics expansion",
            "owner_name": "Maya Chen",
            "stage": "Proposal",
            "status": "stalling",
            "close_date": "2026-04-30",
            "amount_usd": 120000,
            "forecast_probability": 0.45,
        },
        {
            "record_type": "deal",
            "tenant_id": tenant_id,
            "deal_id": DEMO_ATLAS_DEAL_ID,
            "id": DEMO_ATLAS_DEAL_ID,
            "account_name": "Atlas Medical Group",
            "name": "Atlas platform renewal",
            "owner_name": "Owen Patel",
            "stage": "Legal Review",
            "status": "healthy",
            "close_date": "2026-03-28",
            "amount_usd": 92000,
            "forecast_probability": 0.84,
        },
        {
            "record_type": "contact",
            "tenant_id": tenant_id,
            "deal_id": deal_id,
            "id": "contact_elena",
            "name": "Elena Park",
            "title": "VP Operations",
            "email": "elena@northstar.example",
            "role": "Champion",
        },
        {
            "record_type": "contact",
            "tenant_id": tenant_id,
            "deal_id": deal_id,
            "id": "contact_marcus",
            "name": "Marcus Chen",
            "title": "CFO",
            "email": "marcus@northstar.example",
            "role": "Economic buyer",
        },
        {
            "record_type": "contact",
            "tenant_id": tenant_id,
            "deal_id": DEMO_ATLAS_DEAL_ID,
            "id": "contact_priya",
            "name": "Priya Shah",
            "title": "Revenue Operations Lead",
            "email": "priya@atlas.example",
            "role": "Champion",
        },
        {
            "record_type": "contact",
            "tenant_id": tenant_id,
            "deal_id": DEMO_ATLAS_DEAL_ID,
            "id": "contact_daniel",
            "name": "Daniel Brooks",
            "title": "Chief Operating Officer",
            "email": "daniel@atlas.example",
            "role": "Economic buyer",
        },
        {
            "record_type": "contact_memory",
            "contact_id": "contact_elena",
            "deal_id": deal_id,
            "tenant_id": tenant_id,
            "role": "champion",
            "engagement_level": "medium",
            "last_seen_on_call": "call_ns_005",
            "last_seen_timestamp": "2026-03-04T15:18:00.000Z",
            "sentiment_trend": "declining",
            "key_concerns": ["budget_freeze"],
            "valid_from": "2026-03-04T15:00:00.000Z",
            "valid_to": None,
        },
        {
            "record_type": "contact_memory",
            "contact_id": "contact_marcus",
            "deal_id": deal_id,
            "tenant_id": tenant_id,
            "role": "economic_buyer",
            "engagement_level": "silent",
            "last_seen_on_call": "call_ns_001",
            "last_seen_timestamp": "2026-02-04T15:30:00.000Z",
            "sentiment_trend": "neutral",
            "key_concerns": ["business_case"],
            "valid_from": "2026-03-04T15:00:00.000Z",
            "valid_to": None,
        },
        {
            "record_type": "deal_memory",
            "tenant_id": tenant_id,
            "deal_id": deal_id,
            "id": "deal_northstar_expansion:deal_memory:2026-02-04T15:00:00.000Z",
            "stage": "Discovery",
            "champion_id": "contact_elena",
            "economic_buyer_id": "contact_marcus",
            "champion_confidence": 0.82,
            "budget_confirmed": False,
            "technical_validated": False,
            "active_objections": [],
            "next_step_agreed": "Share technical validation plan",
            "last_call_id": "call_ns_001",
            "valid_from": "2026-02-04T15:00:00.000Z",
            "valid_to": "2026-02-18T15:00:00.000Z",
        },
        {
            "record_type": "deal_memory",
            "tenant_id": tenant_id,
            "deal_id": deal_id,
            "id": DEMO_MEMORY_ID,
            "stage": "Proposal",
            "champion_id": "contact_elena",
            "economic_buyer_id": "contact_marcus",
            "champion_confidence": 0.34,
            "budget_confirmed": False,
            "technical_validated": True,
            "active_objections": ["budget_freeze"],
            "next_step_agreed": "Send revised rollout plan to CFO",
            "last_call_id": "call_ns_005",
            "valid_from": "2026-03-04T15:00:00.000Z",
            "valid_to": None,
        },
        {
            "record_type": "deal_memory",
            "tenant_id": tenant_id,
            "deal_id": DEMO_ATLAS_DEAL_ID,
            "id": "deal_atlas_renewal:deal_memory:2026-02-26T17:00:00.000Z",
            "stage": "Legal Review",
            "champion_id": "contact_priya",
            "economic_buyer_id": "contact_daniel",
            "champion_confidence": 0.89,
            "budget_confirmed": True,
            "technical_validated": True,
            "active_objections": [],
            "next_step_agreed": "Procurement to return redlines",
            "last_call_id": "call_at_003",
            "valid_from": "2026-02-26T17:00:00.000Z",
            "valid_to": None,
        },
        {
            "record_type": "call_event",
            "id": "call_ns_001",
            "call_id": "call_ns_001",
            "tenant_id": tenant_id,
            "deal_id": deal_id,
            "timestamp": "2026-02-04T15:00:00.000Z",
            "duration_seconds": 1800,
            "participants": ["contact_elena", "contact_marcus"],
            "objections_raised": [],
            "commitments_made": [
                {
                    "type": "technical_validation",
                    "made_by_contact_id": "contact_elena",
                    "due_date": "2026-02-12",
                    "verbatim": "I will share the technical validation plan.",
                }
            ],
            "sentiment_shifts": [],
            "competitive_mentions": [],
            "champion_behavior": {
                "contact_id": "contact_elena",
                "signal_type": "active_advocacy",
                "evidence_quote": "I can get the rollout team aligned.",
            },
            "summary": "Discovery confirmed technical validation as the next step.",
        },
        {
            "record_type": "call_event",
            "id": "call_ns_005",
            "call_id": "call_ns_005",
            "tenant_id": tenant_id,
            "deal_id": deal_id,
            "timestamp": "2026-03-04T15:00:00.000Z",
            "duration_seconds": 2100,
            "participants": ["contact_elena"],
            "objections_raised": [
                {
                    "type": "budget_freeze",
                    "verbatim_quote": "The CFO froze new platform budget until we rebuild the business case.",
                    "contact_id": "contact_elena",
                    "severity": "high",
                }
            ],
            "commitments_made": [
                {
                    "type": "rollout_plan",
                    "made_by_contact_id": "contact_elena",
                    "due_date": "2026-03-08",
                    "verbatim": "Send me the revised rollout plan and I will take it back to Marcus.",
                }
            ],
            "sentiment_shifts": [
                {
                    "contact_id": "contact_elena",
                    "from": "positive",
                    "to": "negative",
                    "timestamp_in_call": 840,
                    "trigger_quote": "Without the CFO case, I cannot push this forward.",
                }
            ],
            "competitive_mentions": [
                {
                    "competitor_name": "Status quo",
                    "context": "Elena compared the proposal against delaying the rollout.",
                    "sentiment": "negative",
                }
            ],
            "champion_behavior": {
                "contact_id": "contact_elena",
                "signal_type": "silence",
                "evidence_quote": "I need Marcus back in before I advocate internally.",
            },
            "summary": "Budget freeze and CFO silence made the proposal-stage deal risky.",
        },
        {
            "record_type": "call_event",
            "id": "call_at_003",
            "call_id": "call_at_003",
            "tenant_id": tenant_id,
            "deal_id": DEMO_ATLAS_DEAL_ID,
            "timestamp": "2026-02-26T17:00:00.000Z",
            "duration_seconds": 1755,
            "participants": ["contact_priya", "contact_daniel"],
            "objections_raised": [],
            "commitments_made": [
                {
                    "type": "legal_redlines",
                    "made_by_contact_id": "contact_daniel",
                    "due_date": "2026-03-03",
                    "verbatim": "Procurement will return redlines by Tuesday.",
                }
            ],
            "sentiment_shifts": [
                {
                    "contact_id": "contact_daniel",
                    "from": "neutral",
                    "to": "positive",
                    "timestamp_in_call": 804,
                    "trigger_quote": "This is already in the board packet.",
                }
            ],
            "competitive_mentions": [],
            "champion_behavior": {
                "contact_id": "contact_priya",
                "signal_type": "active_advocacy",
                "evidence_quote": "Priya confirmed she added the renewal to Daniel's board packet.",
            },
            "summary": "The renewal advanced to legal with budget confirmed and the security objection resolved.",
        },
        {
            "record_type": "causal_link",
            "id": "causal_budget_freeze_to_cfo_silence",
            "tenant_id": tenant_id,
            "deal_id": deal_id,
            "from_node_id": "call_ns_005",
            "to_node_id": DEMO_MEMORY_ID,
            "link_type": "champion_silence_triggered_budget_objection",
            "confidence": 0.81,
            "evidence_call_id": "call_ns_005",
            "created_at": "2026-03-04T16:00:00.000Z",
        },
        {
            "record_type": "source_fact",
            "id": DEMO_SOURCE_FACT_ID,
            "tenant_id": tenant_id,
            "deal_id": deal_id,
            "source": "crm",
            "source_record_id": "crm_stage_northstar",
            "stage": "Proposal",
            "content": "CRM stage is Proposal after the March 4 call.",
        },
        {
            "record_type": "integration_fact",
            "id": DEMO_INTEGRATION_FACT_ID,
            "tenant_id": tenant_id,
            "deal_id": deal_id,
            "source": "crm",
            "source_record_id": "crm_amount_northstar",
            "stage": "Proposal",
            "content": "CRM amount is 120000.",
            "amount": 120000,
        },
        {
            "record_type": "source_fact",
            "id": "source_fact_atlas_stage",
            "tenant_id": tenant_id,
            "deal_id": DEMO_ATLAS_DEAL_ID,
            "source": "crm",
            "source_record_id": "crm_stage_atlas",
            "stage": "Legal Review",
            "content": "CRM stage is Legal Review after the February 26 renewal call.",
        },
        {
            "record_type": "integration_fact",
            "id": "integration_fact_atlas_amount",
            "tenant_id": tenant_id,
            "deal_id": DEMO_ATLAS_DEAL_ID,
            "source": "crm",
            "source_record_id": "crm_amount_atlas",
            "stage": "Legal Review",
            "content": "CRM amount is 92000.",
            "amount": 92000,
        },
        {
            "record_type": "call_library_entry",
            "id": "call_library_ns_005",
            "tenant_id": tenant_id,
            "call_id": "call_ns_005",
            "deal_id": deal_id,
            "account_id": "account_northstar",
            "title": "Northstar budget freeze follow-up",
            "started_at": "2026-03-04T15:00:00.000Z",
            "duration_seconds": 2100,
            "primary_rep_id": "user_maya",
            "outcome": "budget risk identified",
            "recording_url": None,
            "transcript_id": "transcript_call_ns_005",
        },
        {
            "record_type": "forecast_submission",
            "id": "forecast_2026_03_maya",
            "tenant_id": tenant_id,
            "period": "2026-03",
            "submitted_by_user_id": "user_maya",
            "forecast_category": "best_case",
            "commit_amount_usd": 92000,
            "best_case_amount_usd": 212000,
            "pipeline_amount_usd": 212000,
            "submitted_at": "2026-03-04T18:00:00.000Z",
        },
        {
            "record_type": "coaching_scorecard",
            "id": "coaching_maya_ns_005",
            "tenant_id": tenant_id,
            "rep_id": "user_maya",
            "call_id": "call_ns_005",
            "deal_id": deal_id,
            "reviewer_user_id": "user_owen",
            "overall_score": 78,
            "strengths": ["clear risk recap"],
            "improvement_areas": ["secure direct CFO next step"],
            "reviewed_at": "2026-03-05T10:00:00.000Z",
        },
        {
            "record_type": "engagement_task",
            "id": "task_followup_cfo",
            "tenant_id": tenant_id,
            "deal_id": deal_id,
            "account_id": "account_northstar",
            "owner_user_id": "user_maya",
            "title": "Send revised CFO rollout plan",
            "due_date": "2026-03-08",
            "priority": "high",
            "status": "open",
            "source_call_id": "call_ns_005",
        },
        {
            "record_type": "engagement_task",
            "id": "task_atlas_redlines",
            "tenant_id": tenant_id,
            "deal_id": DEMO_ATLAS_DEAL_ID,
            "account_id": "account_atlas",
            "owner_user_id": "user_owen",
            "title": "Check procurement redlines",
            "due_date": "2026-03-03",
            "priority": "medium",
            "status": "open",
            "source_call_id": "call_at_003",
        },
        {
            "record_type": "assistant_answer",
            "id": "assistant_answer_northstar_risk",
            "tenant_id": tenant_id,
            "question": "why is Northstar risky?",
            "answer": "Northstar is risky because CFO budget approval stalled after champion silence.",
            "citation_ids": ["call_ns_005", DEMO_MEMORY_ID],
            "created_at": "2026-03-04T18:05:00.000Z",
            "created_by_user_id": "user_maya",
        },
        {
            "record_type": "audit_event",
            "id": "audit_export_pipeline_snapshot",
            "tenant_id": tenant_id,
            "actor_user_id": "user_maya",
            "action": "export.created",
            "target_type": "export_job",
            "target_id": "export_pipeline_snapshot",
            "occurred_at": "2026-03-04T18:10:00.000Z",
        },
        {
            "record_type": "export_job",
            "id": "export_pipeline_snapshot",
            "tenant_id": tenant_id,
            "requested_by_user_id": "user_maya",
            "export_type": "pipeline_snapshot",
            "status": "ready",
            "created_at": "2026-03-04T18:09:00.000Z",
            "completed_at": "2026-03-04T18:10:00.000Z",
            "download_url": "demo://exports/pipeline_snapshot.csv",
        },
    )


def demo_query_deal(tenant_id: str, deal_id: str) -> JsonMap:
    return {"results": list(demo_records(tenant_id, deal_id))}


def demo_pipeline_query(tenant_id: str) -> JsonMap:
    return {"results": list(demo_records(tenant_id, DEMO_DEAL_ID))}


def demo_briefing(deal_id: str) -> DealBriefing:
    if deal_id != DEMO_DEAL_ID:
        raise UpstreamServiceError(service="local-demo", detail=f"missing seeded deal {deal_id}")
    return DealBriefing(
        deal_id=deal_id,
        generated_at="2026-03-04T16:00:00.000Z",
        status_summary="Northstar moved to proposal, but CFO budget freeze evidence makes the commit risky.",
        causal_diagnosis=(
            CausalDiagnosis(
                description="Budget freeze followed the March 4 stakeholder call.",
                causal_chain=("call_ns_005", "budget_freeze", "cfo_silence"),
                evidence_node_ids=("call_ns_005", DEMO_MEMORY_ID),
            ),
        ),
        risk_flags=(RiskFlag(flag="Budget freeze", severity="high", evidence_node_id=DEMO_MEMORY_ID),),
        next_best_actions=(
            NextBestAction(
                action="Confirm the CRM stage with RevOps.",
                rationale="The seeded CRM source fact says the deal is in Proposal.",
                cited_memory_node_id=None,
                cited_knowledge_node_id=DEMO_SOURCE_FACT_ID,
            ),
            NextBestAction(
                action="Rebuild the CFO business case before follow-up.",
                rationale="The latest deal memory cites a budget freeze.",
                cited_memory_node_id=DEMO_MEMORY_ID,
                cited_knowledge_node_id=None,
            ),
        ),
        confidence=0.74,
    )
